version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - go build -o .bin/ -v ./...
  
  context: 
    cmds:
      - task: build
      - ./.bin/context

  test:
    cmds:
      - task: build
      - go test -v ./...
